dist: xenial
language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
- python setup.py install
- pip install -r test-requirements.txt
- pip install git+ssh://git@github.com/threatgrid/softserve-atqc.git#egg=ctrlibrary
script:
- pytest threatresponse --pep8
- pytest -v
before_install:
- openssl aes-256-cbc -K $encrypted_2f6fb0cb339e_key -iv $encrypted_2f6fb0cb339e_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
