dist: xenial
language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
env:
- travis_key_password=992a9493d43ebef17ad6d6d768d0c5649223ba898d8e62c29ec0c72b4ba0b83a
before_install:
- openssl aes-256-cbc -k "$travis_key_password" -d -md sha256 -a -in travis_key.enc -out ~/.ssh/id_rsa
- chmod 400 ~/.ssh/id_rsa
install:
- pip install -r requirements.txt
- python setup.py install
- pip install -r test-requirements.txt
before_script:
- cp ~/build/CiscoSecurity/tr-05-api-module/tests/functional/project.properties.sample ~/build/CiscoSecurity/project.properties
- sed -i "s|ctr_client_id=.*|ctr_client_id=$CLIENT_ID|" ~/build/CiscoSecurity/project.properties
- sed -i "s|ctr_client_password=.*|ctr_client_password=$CLIENT_PASSWORD|" ~/build/CiscoSecurity/project.properties
script:
- pytest threatresponse --pep8
- pytest tests/unit -v
- if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then pytest tests/functional -v; fi
