TOKEN_URL = '/iroh/oauth2/token'
PARENT_INSPECT_URL = '/iroh/iroh-inspect'
INSPECT_URL = '/inspect'
PARENT_ENRICH_URL = '/iroh/iroh-enrich'
ENRICH_DELIBERATE_OBSERVABLES = '/deliberate/observables'
ENRICH_OBSERVE_OBSERVABLES = '/observe/observables'
ENRICH_REFER_OBSERVABLES = '/refer/observables'
